# Generated by Django 5.0 on 2026-04-07 17:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_cart',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
